detectors:
  IrresponsibleModule:
    enabled: false
  TooManyInstanceVariables:
    enabled: false
  TooManyStatements:
    exclude:
      - 'Parser#initialize'
      - 'Parser#perform'
  UncommunicativeVariableName:
    exclude:
      - 'Parser#perform'
  NilCheck:
    exclude:
      - 'ValidatorService#self.valid?'